spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BancoGestao
    username: postgres
    password: postgres # Troque pela senha do seu banco local

  servlet:
    multipart:
      max-file-size: 30MB      # Limite máximo para CADA arquivo individual
      max-request-size: 30MB   # Limite máximo para a soma de todos os dados da requisição
  
  jpa:
    # Desativa a criação automática de tabelas pelo Hibernate, pois usaremos o Flyway
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "engebag8@gmail.com" # Coloque o e-mail que vai enviar as mensagens
    password: "ejkbenopqhctnkcb" # ATENÇÃO: Se for Gmail, precisa gerar uma Senha de App
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true
    baseline-on-migrate: true

api:
  security:
    token:
      secret: ${JWT_SECRET:gestao-ti-2026-super-secret-key}

server:
  port: 7000